[Variables]
;=========================================;
;===========Set These Variables===========;
;=========================================;

;Choose your Weather Location from http://www.weather.com/
WeatherCode=USCT0153

;Choose your Units: m=Metric, i=Imperial;
WeatherUnit=i

;===========Other===========;
ProcessInterval=5
Substitute="&amp;":"&","&quot;":"","&Quot;":"","&lt;br&gt;":"","![CDATA[":"","]]":"","...":"","<":"",">":"","/PRE&gt;":"","PRE&gt;":"","&lt;":""
